use crate::{models::BuildResult, process};
use regex::Regex;
use std::{fs, path::PathBuf, time::Instant};

fn cpp_type(value: &str) -> &str {
    match value.trim() {
        "text" | "string" => "std::string",
        "bool" | "boolean" => "bool",
        "long" => "long long",
        "float" => "float",
        "double" | "number" | "decimal" => "double",
        "char" => "char",
        "void" => "void",
        _ => "int",
    }
}

fn rust_type(value: &str) -> &str {
    match value.trim() {
        "text" | "string" => "String",
        "bool" | "boolean" => "bool",
        "long" => "i64",
        "float" => "f32",
        "double" | "number" | "decimal" => "f64",
        "char" => "char",
        "void" => "()",
        _ => "i32",
    }
}

fn rust_parameters(value: &str) -> (String, String) {
    let mut parameters = Vec::new();
    let mut conversions = String::new();
    for part in value.split(',').filter(|part| !part.trim().is_empty()) {
        let (name, kind) = part.split_once(':').unwrap_or((part, "int"));
        let name = name.trim();
        if matches!(kind.trim(), "text" | "string") {
            parameters.push(format!("{name}: impl Into<String>"));
            conversions.push_str(&format!("    let {name}: String = {name}.into();\n"));
        } else {
            parameters.push(format!("{name}: {}", rust_type(kind)));
        }
    }
    (parameters.join(", "), conversions)
}

fn operators(value: &str, target: &str) -> String {
    if target == "python" {
        // Preserve `!=`: replacing every exclamation mark would produce the
        // invalid Python operator `not =`.
        return value
            .replace(" && ", " and ")
            .replace(" || ", " or ")
            .replace("not ", "not ")
            .replace("true", "True")
            .replace("false", "False");
    }
    value
        .replace(" and ", " && ")
        .replace(" or ", " || ")
        .replace("not ", "!")
}

fn conditional_expression(value: &str, target: &str) -> String {
    let pattern = Regex::new(r"^if\s+(.+?)\s+then\s+(.+?)\s+else\s+(.+)$").unwrap();
    let Some(parts) = pattern.captures(value.trim()) else {
        let value = operators(value.trim(), target);
        if target == "rust" && value.contains('"') && value.contains(" + ") {
            let pieces = value.split(" + ").collect::<Vec<_>>();
            let placeholders = "{}".repeat(pieces.len());
            return format!("format!(\"{placeholders}\", {})", pieces.join(", "));
        }
        return value;
    };
    let condition = operators(&parts[1], target);
    let yes = conditional_expression(&parts[2], target);
    let no = conditional_expression(&parts[3], target);
    match target {
        "python" => format!("{yes} if {condition} else {no}"),
        "rust" => format!("if {condition} {{ {yes} }} else {{ {no} }}"),
        _ => format!("({condition}) ? ({yes}) : ({no})"),
    }
}

pub fn transpile_backend(source: &str, target: &str) -> Result<String, String> {
    match target.to_ascii_lowercase().as_str() {
        "cpp" | "c++" => transpile_cpp(source),
        "rust" | "rs" => transpile_rust(source),
        "javascript" | "js" => transpile_script(source, false),
        "python" | "py" => transpile_script(source, true),
        _ => Err("Цель должна быть cpp, rust, javascript или python".into()),
    }
}

fn transpile_cpp(source: &str) -> Result<String, String> {
    let function = Regex::new(
        r"^(?:public\s+)?fun\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(([^)]*)\)\s*(?:->\s*([^\s{=]+))?\s*\{",
    )
    .unwrap();
    let expression_function = Regex::new(
        r"^(?:public\s+)?fun\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(([^)]*)\)\s*(?:->\s*([^\s=]+))?\s*=\s*(.+)$",
    )
    .unwrap();
    let typed = Regex::new(
        r"^(byte|short|int|long|float|double|number|decimal|text|string|bool|boolean|char)\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.+)$",
    )
    .unwrap();
    let named = Regex::new(r"^(let|const|var)\s+([A-Za-z_][A-Za-z0-9_]*)(?:\s*:\s*([^=\s]+))?\s*=\s*(.+)$").unwrap();
    let range = Regex::new(r"^for\s+(\w+)\s+in\s+(.+?)\.\.(=)?(.+?)\s*\{$").unwrap();
    let mut out = String::from(
        "// Generated by Funo 1.0 — C++17 backend\n#include <iostream>\n#include <string>\n#include <vector>\n#include <unordered_map>\n#include <unordered_set>\n#include <cmath>\n\n",
    );
    for raw in source.lines() {
        let line = raw.trim().trim_end_matches(';').trim();
        if line.is_empty() || line.starts_with("use ") || line.starts_with("package ") {
            continue;
        }
        let indent = "    ".repeat(raw.chars().take_while(|value| value.is_whitespace()).count() / 4);
        if line.starts_with("//") {
            out.push_str(&format!("{indent}{line}\n"));
        } else if let Some(cap) = function.captures(line) {
            let name = &cap[1];
            let params = cap[2]
                .split(',')
                .filter(|part| !part.trim().is_empty())
                .map(|part| {
                    let (name, kind) = part.split_once(':').unwrap_or((part, "int"));
                    format!("{} {}", cpp_type(kind), name.trim())
                })
                .collect::<Vec<_>>()
                .join(", ");
            let result = if name == "main" { "int" } else { cpp_type(cap.get(3).map(|v| v.as_str()).unwrap_or("void")) };
            out.push_str(&format!("{result} {name}({params}) {{\n"));
        } else if let Some(cap) = expression_function.captures(line) {
            let name = &cap[1];
            let params = cap[2]
                .split(',')
                .filter(|part| !part.trim().is_empty())
                .map(|part| {
                    let (name, kind) = part.split_once(':').unwrap_or((part, "int"));
                    format!("{} {}", cpp_type(kind), name.trim())
                })
                .collect::<Vec<_>>()
                .join(", ");
            let result = if name == "main" {
                "int"
            } else {
                cap.get(3).map(|value| cpp_type(value.as_str())).unwrap_or("auto")
            };
            let expression = cap[4].trim();
            out.push_str(&format!("{result} {name}({params}) {{\n"));
            if let Some(value) = expression.strip_prefix("println(").and_then(|value| value.strip_suffix(')')) {
                out.push_str(&format!("    std::cout << {} << std::endl;\n", operators(value, "cpp")));
                if name == "main" { out.push_str("    return 0;\n"); }
            } else if let Some(value) = expression.strip_prefix("print(").and_then(|value| value.strip_suffix(')')) {
                out.push_str(&format!("    std::cout << {};\n", operators(value, "cpp")));
                if name == "main" { out.push_str("    return 0;\n"); }
            } else if name == "main" {
                out.push_str(&format!("    (void)({});\n    return 0;\n", conditional_expression(expression, "cpp")));
            } else {
                out.push_str(&format!("    return {};\n", conditional_expression(expression, "cpp")));
            }
            out.push_str("}\n");
        } else if line == "}" {
            out.push_str(&format!("{indent}}}\n"));
        } else if let Some(cap) = typed.captures(line) {
            out.push_str(&format!("{indent}{} {} = {};\n", cpp_type(&cap[1]), &cap[2], operators(&cap[3], "cpp")));
        } else if let Some(cap) = named.captures(line) {
            let final_prefix = if &cap[1] == "var" { "" } else { "const " };
            let kind = cap.get(3).map(|value| cpp_type(value.as_str())).unwrap_or("auto");
            out.push_str(&format!("{indent}{final_prefix}{kind} {} = {};\n", &cap[2], operators(&cap[4], "cpp")));
        } else if let Some(cap) = range.captures(line) {
            let comparison = if cap.get(3).is_some() { "<=" } else { "<" };
            out.push_str(&format!("{indent}for (int {} = {}; {} {comparison} {}; ++{}) {{\n", &cap[1], &cap[2], &cap[1], &cap[4], &cap[1]));
        } else if let Some(value) = line.strip_prefix("println(").and_then(|v| v.strip_suffix(')')) {
            out.push_str(&format!("{indent}std::cout << {} << std::endl;\n", operators(value, "cpp")));
        } else if let Some(value) = line.strip_prefix("print(").and_then(|v| v.strip_suffix(')')) {
            out.push_str(&format!("{indent}std::cout << {};\n", operators(value, "cpp")));
        } else if line == "return(200)" {
            out.push_str(&format!("{indent}return 0;\n"));
        } else if let Some(value) = line.strip_prefix("return(").and_then(|v| v.strip_suffix(')')) {
            out.push_str(&format!("{indent}return {};\n", operators(value, "cpp")));
        } else if let Some(condition) = line.strip_prefix("if ").and_then(|v| v.strip_suffix('{')) {
            out.push_str(&format!("{indent}if ({}) {{\n", operators(condition.trim(), "cpp")));
        } else if let Some(condition) = line.strip_prefix("while ").and_then(|v| v.strip_suffix('{')) {
            out.push_str(&format!("{indent}while ({}) {{\n", operators(condition.trim(), "cpp")));
        } else if line.starts_with("else") || line.starts_with("} else") {
            out.push_str(&format!("{indent}{line}\n"));
        } else {
            out.push_str(&format!("{indent}{};\n", operators(line, "cpp")));
        }
    }
    if !out.contains("int main(") {
        return Err("Для C++ backend нужна функция fun main()".into());
    }
    Ok(out)
}

fn transpile_rust(source: &str) -> Result<String, String> {
    let function = Regex::new(
        r"^(?:public\s+)?fun\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(([^)]*)\)\s*(?:->\s*([^\s{=]+))?\s*\{",
    )
    .unwrap();
    let expression_function = Regex::new(
        r"^(?:public\s+)?fun\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(([^)]*)\)\s*(?:->\s*([^\s=]+))?\s*=\s*(.+)$",
    )
    .unwrap();
    let typed = Regex::new(
        r"^(byte|short|int|long|float|double|number|decimal|text|string|bool|boolean|char)\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.+)$",
    )
    .unwrap();
    let named = Regex::new(r"^(let|const|var)\s+([A-Za-z_][A-Za-z0-9_]*)(?:\s*:\s*([^=\s]+))?\s*=\s*(.+)$").unwrap();
    let range = Regex::new(r"^for\s+(\w+)\s+in\s+(.+?)\.\.(=)?(.+?)\s*\{$").unwrap();
    let mut out = String::from("// Generated by Funo 1.0 — Rust backend\n\n");
    for raw in source.lines() {
        let line = raw.trim().trim_end_matches(';').trim();
        if line.is_empty() || line.starts_with("use ") || line.starts_with("package ") {
            continue;
        }
        let indent = "    ".repeat(raw.chars().take_while(|value| value.is_whitespace()).count() / 4);
        if let Some(cap) = function.captures(line) {
            let name = &cap[1];
            let (params, conversions) = rust_parameters(&cap[2]);
            let result = if name == "main" {
                String::new()
            } else {
                cap.get(3)
                    .map(|value| format!(" -> {}", rust_type(value.as_str())))
                    .unwrap_or_default()
            };
            out.push_str(&format!("fn {name}({params}){result} {{\n{conversions}"));
        } else if let Some(cap) = expression_function.captures(line) {
            let name = &cap[1];
            let (params, conversions) = rust_parameters(&cap[2]);
            let result = if name == "main" {
                String::new()
            } else {
                cap.get(3)
                    .map(|value| format!(" -> {}", rust_type(value.as_str())))
                    .unwrap_or_default()
            };
            let expression = cap[4].trim();
            out.push_str(&format!("fn {name}({params}){result} {{\n{conversions}"));
            if let Some(value) = expression.strip_prefix("println(").and_then(|value| value.strip_suffix(')')) {
                out.push_str(&format!("    println!(\"{{}}\", {});\n", operators(value, "rust")));
            } else if let Some(value) = expression.strip_prefix("print(").and_then(|value| value.strip_suffix(')')) {
                out.push_str(&format!("    print!(\"{{}}\", {});\n", operators(value, "rust")));
            } else if name == "main" {
                out.push_str(&format!("    let _ = {};\n", conditional_expression(expression, "rust")));
            } else {
                out.push_str(&format!("    {}\n", conditional_expression(expression, "rust")));
            }
            out.push_str("}\n");
        } else if let Some(cap) = typed.captures(line) {
            let expression = cap[3].trim();
            let value = if matches!(&cap[1], "text" | "string") && expression.starts_with('"') && !expression.contains(" + ") {
                format!("{expression}.to_string()")
            } else {
                conditional_expression(expression, "rust")
            };
            out.push_str(&format!("{indent}let mut {}: {} = {value};\n", &cap[2], rust_type(&cap[1])));
        } else if let Some(cap) = named.captures(line) {
            let mutable = if &cap[1] == "var" { "mut " } else { "" };
            let declared_type = cap.get(3).map(|value| value.as_str());
            let annotation = declared_type.map(|value| format!(": {}", rust_type(value))).unwrap_or_default();
            let expression = cap[4].trim();
            let value = if declared_type.is_some_and(|value| matches!(value.trim(), "text" | "string")) && expression.starts_with('"') && !expression.contains(" + ") {
                format!("{expression}.to_string()")
            } else {
                conditional_expression(&cap[4], "rust")
            };
            out.push_str(&format!("{indent}let {mutable}{}{annotation} = {value};\n", &cap[2]));
        } else if let Some(cap) = range.captures(line) {
            let dots = if cap.get(3).is_some() { "..=" } else { ".." };
            out.push_str(&format!("{indent}for {} in {}{dots}{} {{\n", &cap[1], &cap[2], &cap[4]));
        } else if let Some(value) = line.strip_prefix("println(").and_then(|v| v.strip_suffix(')')) {
            out.push_str(&format!("{indent}println!(\"{{}}\", {});\n", operators(value, "rust")));
        } else if let Some(value) = line.strip_prefix("print(").and_then(|v| v.strip_suffix(')')) {
            out.push_str(&format!("{indent}print!(\"{{}}\", {});\n", operators(value, "rust")));
        } else if line == "return(200)" {
            out.push_str(&format!("{indent}return;\n"));
        } else if let Some(condition) = line.strip_prefix("if ").and_then(|v| v.strip_suffix('{')) {
            out.push_str(&format!("{indent}if {} {{\n", operators(condition.trim(), "rust")));
        } else if let Some(condition) = line.strip_prefix("while ").and_then(|v| v.strip_suffix('{')) {
            out.push_str(&format!("{indent}while {} {{\n", operators(condition.trim(), "rust")));
        } else {
            out.push_str(&format!("{indent}{}{}\n", operators(line, "rust"), if matches!(line, "{" | "}") || line.ends_with('{') { "" } else { ";" }));
        }
    }
    if !out.contains("fn main(") {
        return Err("Для Rust backend нужна функция fun main()".into());
    }
    Ok(out)
}

fn transpile_script(source: &str, python: bool) -> Result<String, String> {
    let function = Regex::new(r"^(?:public\s+)?fun\s+(\w+)\(([^)]*)\)(?:\s*->\s*[^\s{]+)?\s*\{").unwrap();
    let expression_function = Regex::new(r"^(?:public\s+)?fun\s+(\w+)\(([^)]*)\)(?:\s*->\s*[^\s=]+)?\s*=\s*(.+)$").unwrap();
    let declaration = Regex::new(r"^(?:let|var|const|byte|short|int|long|float|double|number|decimal|text|string|bool|boolean|char)\s+(\w+)(?:\s*:\s*[^=\s]+)?\s*=\s*(.+)$").unwrap();
    let range = Regex::new(r"^for\s+(\w+)\s+in\s+(.+?)\.\.(=)?(.+?)\s*\{$").unwrap();
    let mut out = format!("{} Generated by Funo 1.0\n", if python { "#" } else { "//" });
    let mut depth = 0usize;
    let mut saw_main = false;
    for raw in source.lines() {
        let mut line = raw.trim().trim_end_matches(';').trim();
        if line.is_empty() || line.starts_with("use ") || line.starts_with("package ") {
            continue;
        }
        if line.starts_with("//") {
            out.push_str(&format!("{}{}{}\n", "    ".repeat(if python { depth } else { 0 }), if python { "#" } else { "//" }, line.trim_start_matches("//")));
            continue;
        }
        let closes_then_opens = line.starts_with('}') && line[1..].trim_start().starts_with("else");
        if line == "}" || closes_then_opens {
            depth = depth.saturating_sub(1);
            if line == "}" {
                if !python { out.push_str("}\n"); }
                continue;
            }
            line = line.trim_start_matches('}').trim();
        }
        let indent = if python { "    ".repeat(depth) } else { String::new() };
        if let Some(cap) = function.captures(line) {
            if &cap[1] == "main" { saw_main = true; }
            let params = cap[2]
                .split(',')
                .filter(|value| !value.trim().is_empty())
                .map(|value| value.split_once(':').map(|pair| pair.0).unwrap_or(value).trim())
                .collect::<Vec<_>>()
                .join(", ");
            out.push_str(&format!("{indent}{} {}({params}){}\n", if python { "def" } else { "function" }, &cap[1], if python { ":" } else { " {" }));
            depth += 1;
        } else if let Some(cap) = expression_function.captures(line) {
            let name = &cap[1];
            if name == "main" { saw_main = true; }
            let params = cap[2]
                .split(',')
                .filter(|value| !value.trim().is_empty())
                .map(|value| value.split_once(':').map(|pair| pair.0).unwrap_or(value).trim())
                .collect::<Vec<_>>()
                .join(", ");
            let expression = cap[3].trim();
            let target = if python { "python" } else { "javascript" };
            out.push_str(&format!("{indent}{} {}({params}){}\n", if python { "def" } else { "function" }, name, if python { ":" } else { " {" }));
            let body_indent = if python { format!("{indent}    ") } else { "    ".into() };
            if let Some(value) = expression.strip_prefix("println(").and_then(|value| value.strip_suffix(')')) {
                out.push_str(&format!("{body_indent}{}({}){}\n", if python { "print" } else { "console.log" }, operators(value, target), if python { "" } else { ";" }));
            } else if name == "main" {
                out.push_str(&format!("{body_indent}{}{}\n", conditional_expression(expression, target), if python { "" } else { ";" }));
            } else {
                out.push_str(&format!("{body_indent}return {}{}\n", conditional_expression(expression, target), if python { "" } else { ";" }));
            }
            if !python { out.push_str("}\n"); }
        } else if let Some(cap) = range.captures(line) {
            if python {
                let end = if cap.get(3).is_some() { format!("({}) + 1", &cap[4]) } else { cap[4].to_string() };
                out.push_str(&format!("{indent}for {} in range({}, {end}):\n", &cap[1], &cap[2]));
            } else {
                let comparison = if cap.get(3).is_some() { "<=" } else { "<" };
                out.push_str(&format!("for (let {} = {}; {} {comparison} {}; {}++) {{\n", &cap[1], &cap[2], &cap[1], &cap[4], &cap[1]));
            }
            depth += 1;
        } else if let Some(condition) = line.strip_prefix("if ").and_then(|value| value.strip_suffix('{')) {
            out.push_str(&format!("{indent}if {}{}\n", if python { operators(condition.trim(), "python") } else { format!("({})", operators(condition.trim(), "javascript")) }, if python { ":" } else { " {" }));
            depth += 1;
        } else if let Some(condition) = line.strip_prefix("while ").and_then(|value| value.strip_suffix('{')) {
            out.push_str(&format!("{indent}while {}{}\n", if python { operators(condition.trim(), "python") } else { format!("({})", operators(condition.trim(), "javascript")) }, if python { ":" } else { " {" }));
            depth += 1;
        } else if line.starts_with("else") {
            out.push_str(&format!("{indent}{}else{}\n", if !python && closes_then_opens { "} " } else { "" }, if python { ":" } else { " {" }));
            depth += 1;
        } else if let Some(cap) = declaration.captures(line) {
            let prefix = if python { "" } else { "let " };
            out.push_str(&format!("{indent}{prefix}{} = {}{}\n", &cap[1], operators(&cap[2], if python { "python" } else { "javascript" }), if python { "" } else { ";" }));
        } else if let Some(value) = line.strip_prefix("println(").and_then(|value| value.strip_suffix(')')) {
            out.push_str(&format!("{indent}{}({}){}\n", if python { "print" } else { "console.log" }, operators(value, if python { "python" } else { "javascript" }), if python { "" } else { ";" }));
        } else if let Some(value) = line.strip_prefix("print(").and_then(|value| value.strip_suffix(')')) {
            let value = operators(value, if python { "python" } else { "javascript" });
            if python {
                out.push_str(&format!("{indent}print({value}, end=\"\")\n"));
            } else {
                out.push_str(&format!("{indent}process.stdout.write(String({value}));\n"));
            }
        } else if line == "return(200)" {
            out.push_str(&format!("{indent}return{}\n", if python { "" } else { ";" }));
        } else if let Some(value) = line.strip_prefix("return(").and_then(|value| value.strip_suffix(')')) {
            out.push_str(&format!("{indent}return {}{}\n", operators(value, if python { "python" } else { "javascript" }), if python { "" } else { ";" }));
        } else {
            out.push_str(&format!("{indent}{}{}\n", operators(line, if python { "python" } else { "javascript" }), if python || line.ends_with('{') { "" } else { ";" }));
        }
    }
    if !saw_main {
        return Err(format!("Для {} backend нужна функция fun main()", if python { "Python" } else { "JavaScript" }));
    }
    out.push_str(if python { "\nif __name__ == \"__main__\":\n    main()\n" } else { "\nmain();\n" });
    Ok(out)
}

pub fn build_backend(project_root: &str, source: &str, target: &str, run: bool) -> BuildResult {
    let started = Instant::now();
    let generated = match transpile_backend(source, target) {
        Ok(value) => value,
        Err(error) => return failed(error, String::new(), started),
    };
    let root = PathBuf::from(project_root);
    if !root.is_absolute() {
        return failed("Путь проекта должен быть абсолютным".into(), generated, started);
    }
    let build = root.join(".funo").join("native").join(target.to_ascii_lowercase());
    if let Err(error) = fs::create_dir_all(&build) {
        return failed(error.to_string(), generated, started);
    }
    let normalized = target.to_ascii_lowercase();
    let (source_name, artifact_name) = match normalized.as_str() {
        "cpp" | "c++" => ("main.cpp", if cfg!(windows) { "funo-app.exe" } else { "funo-app" }),
        "rust" | "rs" => ("main.rs", if cfg!(windows) { "funo-app.exe" } else { "funo-app" }),
        "javascript" | "js" => ("main.js", "main.js"),
        _ => ("main.py", "main.py"),
    };
    let source_path = build.join(source_name);
    if let Err(error) = fs::write(&source_path, &generated) {
        return failed(error.to_string(), generated, started);
    }
    let artifact = build.join(artifact_name);
    let command_result = match normalized.as_str() {
        "cpp" | "c++" => process::command("c++")
            .arg("-std=c++17")
            .arg(&source_path)
            .arg("-o")
            .arg(&artifact)
            .output(),
        "rust" | "rs" => process::command("rustc")
            .arg("--edition=2021")
            .arg(&source_path)
            .arg("-o")
            .arg(&artifact)
            .output(),
        "javascript" | "js" if run => process::command("node").arg(&source_path).output(),
        "python" | "py" if run => process::command(if cfg!(windows) { "python" } else { "python3" }).arg(&source_path).output(),
        _ => {
            return BuildResult {
                success: true,
                stdout: format!("Исходник создан: {}", source_path.display()),
                stderr: String::new(),
                generated_java: generated,
                elapsed_ms: started.elapsed().as_millis(),
                diagnostics: Vec::new(),
                artifact: Some(source_path.to_string_lossy().to_string()),
            }
        }
    };
    let output = match command_result {
        Ok(value) => value,
        Err(error) => return failed(format!("Компилятор {target} не найден: {error}"), generated, started),
    };
    if !output.status.success() {
        return failed(String::from_utf8_lossy(&output.stderr).to_string(), generated, started);
    }
    if run && matches!(normalized.as_str(), "cpp" | "c++" | "rust" | "rs") {
        match process::command(&artifact).output() {
            Ok(value) => {
                return BuildResult {
                    success: value.status.success(),
                    stdout: String::from_utf8_lossy(&value.stdout).trim_end().into(),
                    stderr: String::from_utf8_lossy(&value.stderr).trim_end().into(),
                    generated_java: generated,
                    elapsed_ms: started.elapsed().as_millis(),
                    diagnostics: Vec::new(),
                    artifact: Some(artifact.to_string_lossy().into()),
                }
            }
            Err(error) => return failed(error.to_string(), generated, started),
        }
    }
    BuildResult {
        success: true,
        stdout: String::from_utf8_lossy(&output.stdout).trim_end().into(),
        stderr: String::new(),
        generated_java: generated,
        elapsed_ms: started.elapsed().as_millis(),
        diagnostics: Vec::new(),
        artifact: Some(artifact.to_string_lossy().into()),
    }
}

fn failed(error: String, generated: String, started: Instant) -> BuildResult {
    BuildResult {
        success: false,
        stdout: String::new(),
        stderr: error,
        generated_java: generated,
        elapsed_ms: started.elapsed().as_millis(),
        diagnostics: Vec::new(),
        artifact: None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn emits_cpp_and_rust_entrypoints() {
        let source = "fun main() {\n    int score = 2\n    score += 3\n    println(score)\n    return(200)\n}";
        assert!(transpile_backend(source, "cpp").unwrap().contains("int main()"));
        assert!(transpile_backend(source, "rust").unwrap().contains("fn main()"));
    }

    #[test]
    fn emits_valid_script_constructs() {
        let source = "fun double(n: int) -> int = if n != 0 then n * 2 else 0\nfun greet(name: text) {\n    println(name)\n}\nfun main() {\n    for i in 0..3 {\n        greet(\"Funo\")\n    }\n}";
        let javascript = transpile_backend(source, "javascript").unwrap();
        assert!(javascript.contains("function double(n) {"));
        assert!(javascript.contains("return (n != 0) ? (n * 2) : (0);"));
        assert!(javascript.contains("function greet(name) {"));
        assert!(javascript.contains("console.log(name);"));
        assert!(javascript.contains("for (let i = 0; i < 3; i++)"));
        let python = transpile_backend(source, "python").unwrap();
        assert!(python.contains("def double(n):"));
        assert!(python.contains("return n * 2 if n != 0 else 0"));
        assert!(python.contains("def greet(name):"));
        assert!(python.contains("print(name)"));
        assert!(python.contains("for i in range(0, 3):"));
    }
}
